# Streamlit Cloud Secrets 설정 예시
# 
# 사용법:
# 1. Streamlit Cloud 대시보드 접속
# 2. 앱 선택 → Settings → Secrets
# 3. 아래 내용을 복사해서 붙여넣기
# 4. 실제 값으로 변경

# OpenAI
OPENAI_API_KEY = "sk-proj-xxxxx"

# Confluence
CONFLUENCE_URL = "https://woowahanbros.atlassian.net"
# Note: Username, Token, Space는 사용자가 UI에서 입력

# Slack
SLACK_BOT_TOKEN = "xoxb-xxxxx"  # 공용 Bot Token만 필요
# Note: 채널은 사용자가 UI에서 입력

